---
deployment :
    tasks :
        - export DEPLOYPATH=/home/jamiesco/public_html/
        - /bin/cp \*.html $DEPLOYPATH 
        - /bin/cp \*.css $DEPLOYPATH
        - /bin/cp \*.jpg $DEPLOYPATH
        - /bin/cp \*.png $DEPLOYPATH
